/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedLayoutImport } from './routes/_protected/_layout'
import { Route as ProtectedLayoutChatsImport } from './routes/_protected/_layout.chats'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedLayoutChatsRoute = ProtectedLayoutChatsImport.update({
  path: '/chats',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_layout': {
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/_layout/chats': {
      preLoaderRoute: typeof ProtectedLayoutChatsImport
      parentRoute: typeof ProtectedLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ProtectedRoute.addChildren([
    ProtectedLayoutRoute.addChildren([ProtectedLayoutChatsRoute]),
  ]),
  RegisterRoute,
])

/* prettier-ignore-end */
